# Generated by Django 3.2.6 on 2021-09-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_album_num_stars'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
    ]
